development:
  dialect: mysql
  database: blinkpay
  user: boris
  password: {{env "DATABASE_PASSWORD_BORIS"}
  host: 127.0.0.1
  port: 3306
  pool: 5

test:
  url: {{env "TEST_DATABASE_URL"}}

production:
  url: {{env "DATABASE_URL"}}
